### ISSUE TITLE
Update status tests

### ISSUE THREAD

**Issue by greatfire-martin** [Behemouth/website-mirror-by-proxy#10]
See https://github.com/greatfire/website-mirror-by-proxy/tree/master/public/status_tests

**Comment by Behemouth** [comment]
The api url need to be config in `conf-local.inc`:
 `Conf::$dns_poisoning_test_api="https://example.com/api/";`

BTW: With many times git push hang 100% then fail, I found I have to use `tracepath github.com` to find mtu,then `sudo ip link set dev eth0 mtu 960` solved it. :cry:
