### ISSUE TITLE
Boxun: several Google.com URLs are not proxied

### ISSUE THREAD

**Issue by greatfire-martin** [Behemouth/website-mirror-by-proxy#3]
This will cause the website to keep loading until the request time out. The requests should be proxied through WMBP.

**Comment by Behemouth** [comment]
Which page? I can't find any `google.com` request on Boxun. 
Only  this bad link :
https://www.googletagadservices.com/tag/js/gpt.js 
But it is always connection refused.

If `google-analytics.com` and `googlesyndication.com` domains need to be proxied,we can add it to conf-local.inc

**Comment by greatfire-martin** [comment]
Analytics should not be proxied.

But https://www.googletagadservices.com/tag/js/gpt.js should be.

I saw some google.com URLs before but don't see them now, not sure why. Anyway, please test the site on a connection behind the GFW to make sure there aren't resources which block the site or which makes it load until they time out.

**Comment by Behemouth** [comment]
Yes,I test it behind the GFW.

The  https://www.googletagadservices.com/tag/js/gpt.js seems like a bad link. It is still connection refused when I'm VPN On.

**Comment by greatfire-martin** [comment]
https://www.googletagadservices.com/tag/js/gpt.js is indeed a bad link. But boxun.com calls "http://www.googletagadservices.com/tag/js/gpt.js" (not https) which works. I guess our system rewrites this to HTTPS? Should be fixable with a rewrite.

**Comment by Behemouth** [comment]
Removed 

```
TextInternalUrlFilters::addSearch('http://www.googletagadservices.com', 'https://www.googletagadservices.com');
```

and TextExternalUrlFilters::addHosts `'www.googletagadservices.com'` fixed it.
