### ISSUE TITLE
Boxun: https://gae.caspion.com/cas.js fails

### ISSUE THREAD

**Issue by greatfire-martin** [Behemouth/website-mirror-by-proxy#4]
It's proxied but the server returns a 500 error

**Comment by Behemouth** [comment]
Because the source url's CA has expired.

**Comment by greatfire-martin** [comment]
Then can it load http://gae.caspion.com/cas.js instead?

**Comment by Behemouth** [comment]
I'll add this code to `conf-local.inc`:

```
TextInternalUrlFilters::addSearch('https://gae.caspion.com/cas.js','http://gae.caspion.com/cas.js');
```

Which page do you find this request? So that I can test if it worked.

BTW: Do we have an all sites' config repository?

**Comment by greatfire-martin** [comment]
For example https://d2zgypnhn7mm3b.cloudfront.net/news/gb/china/2015/03/201503110422.shtml.

No we don't have such a repo, but we probably should - good idea.

**Comment by Behemouth** [comment]
I updated `conf-local.inc` in the server,then get an error : 

```
Mixed Content: The page at 'https://d2zgypnhn7mm3b.cloudfront.net/news/gb/china/2015/03/201503110422.shtml' was loaded over HTTPS, but requested an insecure resource 'http://gae.caspion.com/r/static/ads/matomy-160x600.html'. This request has been blocked; the content must be served over HTTPS.
```

Because the ad request was made by dynamic javascript.It is hard to fix in current version.
I suggest we leave this problem to the future plan.

**Comment by greatfire-martin** [comment]
I think this can be fixed. The source website calls it like this:

```
<script type="text/javascript" src="//gae.caspion.com/cas.js"></script>
```

WMBP replaces // style URLs with a default HTTPS protocol. Since boxun.com isn't available on HTTPS, this error doesn't affect it. But on our mirrors it does. We could prevent it by manually replacing "https://gae.caspion.com" with "./http://gae.caspion.com". Eg:

```
TextInternalUrlFilters::addSearch('https://gae.caspion.com','./http://gae.caspion.com');
```

**Comment by Behemouth** [comment]
Can be fixed like this,but we need to proxy doubleclick too,because the ad is returned by doubleclick.

```
TextInternalUrlFilters::addSearch('"//gae.caspion.com','"http://gae.caspion.com');
TextInternalUrlFilters::addSearch('https://gae.caspion.com','http://gae.caspion.com');
```

Shall we?

**Comment by greatfire-martin** [comment]
Why do we need to proxy doubleclick? The...

```
<script type="text/javascript" src="//gae.caspion.com/cas.js"></script>
```

... script is embedded in the main HTML, eg on http://boxun.com/news/gb/intl/2015/03/201503112319.shtml#.VQFfa-mUfCI.

Generally I don't think proxying ads is a good idea. The ad company might treat it as fraud, if all the clicks come from one IP address.

**Comment by Behemouth** [comment]
Because `cas.js` loads `http://pagead2.googlesyndication.com/pagead/show_ads.js`,then the later loads `https://pagead2.googlesyndication.com/pagead/js/r20150310/r20150224/show_ads_impl.js`,then the later loads `https://pagead2.googlesyndication.com/pagead/js/r20150310/r20150224/show_ads_impl.js`,which loads `http://gae.caspion.com/r/static/ads/matomy-160x600.html`. That is out of our control. We can fix loading `cas.js`,but it doesn't make sense unless we proxy doubleclick too.

**Comment by greatfire-martin** [comment]
Got it. Just disable it then.

**Comment by Behemouth** [comment]
Now just simple config as addHosts `'gae.caspion.com'` and 

```
TextInternalUrlFilters::addSearch('"//gae.caspion.com','"http://gae.caspion.com');
TextInternalUrlFilters::addSearch('https://gae.caspion.com','http://gae.caspion.com');
```

in case of this dead script  block the page body to show.
