### ISSUE TITLE
Redirection when blocked not stable

### ISSUE THREAD

**Issue by greatfire-martin** [Behemouth/website-mirror-by-proxy#6]
Simulating DNS poisoning, the page is indeed cached, but redirection isn't stable. I can see that the site attempts to access appcache files on other domains, but it never redirects to them. Tested in Chrome.

**Comment by Behemouth** [comment]
The request timeout is 10s. It will try current mirror first,if it was blocked,then try all other mirrors and pick the fastest one,redirect to that domain.

**Comment by greatfire-martin** [comment]
That's not what happened when I tested. It kept reloading the same URL. Please run more testing. Perhaps there are certain conditions which makes it fail.

**Comment by Behemouth** [comment]
I think it is caused by too short timeout,I've increased it to 30s now.
